name: Update README

on: push
    # schedule:
    #     - cron: '30 18 * * *'
jobs:
    update-readme:
        name: Update README with metrics
        runs-on: ubuntu-latest
        steps:
            -
                name: Repositories traffic
                uses: lowlighter/metrics@latest
                with:
                  filename: metrics.plugin.traffic.svg
                  token: ${{ secrets.GH_TOKEN }}
                  base: repositories
                  plugin_traffic: yes
        
            -
                name: Half-year calendar
                uses: lowlighter/metrics@latest
                with:
                    filename: metrics.plugin.isocalendar.svg
                    token: ${{ secrets.GH_TOKEN }}
                    base: ""
                    plugin_isocalendar: yes